<?php
function show_header(){
echo "
<!DOCTYPE html>
<html><head>
<link rel='shortcut icon' href='favicon.ico'>
<link rel='stylesheet' href='/style.css'>
<script src='js/script.js'></script>
<script src='/js/vendor/jquery.ui.widget.js'></script>
<script src='/js/jquery.iframe-transport.js'></script>
<script src='/js/jquery.fileupload.js'></script>
<title>Crawler Test</title>
</head><body><div id='content'>";
                      }
?>
